### ISSUE TITLE
相应的仓库尚未准备好相关的包

### ISSUE THREAD

**Issue by lunrenyi** [x-cmd/pkg#23]
win/x64:
  - magick、zenith、pierrot、bandwhich、mirrord、tig、zellij、bun
 
linux/x64:
  - grails、infrastructor
  
linux/arm64:
  - ucloud: 包有问题，下载后提示文件为非压缩文件，无法解压

**Comment by padparadsayc** [comment]
具体错误信息的截图在这个 job 里面搜索就好

https://github.com/x-cmd/pkg/actions/runs/4911091365/jobs/8768814039

<img width="1097" alt="image" src="https://user-images.githubusercontent.com/89379653/236777219-bf87ff63-4a8c-4e0b-a3ca-e283f295974e.png">

**Comment by tzw-my** [comment]
### win/x64
- magick windows 版本113M，所以暂时没有放上去，后面补
- zenith 不支持windows, pkg应该有相应的提示吧?
- pierrot @mnnna 
- bandwhich 后面加

### linux/x64
- magick tig zellij zenith 应该都有
- 其余 @mnnna

**Comment by padparadsayc** [comment]
不支持的需要在对应的 yml 里面移除掉对应的 os/arch

**Comment by tzw-my** [comment]
> 不支持的需要在对应的yml里面移去对应的os/arch

<img width="1214" alt="企业微信截图_897c0606-ba75-4342-815e-06fa51b9788e" src="https://user-images.githubusercontent.com/57086746/236779329-689f12ba-2bbb-4701-9035-2f727590fb12.png">
x-cmd/pkg yml里面本来也没有写，所以这是一个Bug @mnnna

**Comment by tzw-my** [comment]
> win/x64:
> 
> * magick、zenith、pierrot、bandwhich
> 
> linux/x64:
> 
> * magick、mirrord、tig、zellij、zenith、bun、grails、infrastructor

再确认一下linux/x64是真有问题，你提出的似乎不对

**Comment by tzw-my** [comment]
bandwhich 版本号错了
![image](https://user-images.githubusercontent.com/57086746/236791706-3fb1beca-eb78-4a38-b918-6f727f966172.png)
下载的log url都不对 @mnnna

**Comment by mnnna** [comment]
> ncat nmap nping 和traceroute国内都是可以的， 国外的url挂了
![image](https://user-images.githubusercontent.com/100188748/236794949-ea89a2e9-0223-48af-af13-fc2de40532d8.png)
![image](https://user-images.githubusercontent.com/100188748/236795104-1af8c0d8-e874-47c9-8706-bc4985a1be05.png)
![image](https://user-images.githubusercontent.com/100188748/236795172-d27439cb-2578-498f-8baf-a4a67694ac1b.png)
![image](https://user-images.githubusercontent.com/100188748/236795307-6d91ddf8-3426-4974-b01b-e89d981afc9e.png)

internet：
https://raw.githubusercontent.com/static-build/nmap/main/nmap/7.92/nmap.linux.x64.7z
https://raw.githubusercontent.com/static-build/nmap/main/nping/7.92/nping.linux.x64.7z
@tzw-my

**Comment by tzw-my** [comment]
<img width="1001" alt="image" src="https://user-images.githubusercontent.com/57086746/236797750-76ffb739-f926-4dc3-8321-eb1c3ed5c05c.png">
没有挂吧~，本来就是拿到数字才知道要下载几个分卷的包的

**Comment by mnnna** [comment]
> <img alt="image" width="1001" src="https://user-images.githubusercontent.com/57086746/236797750-76ffb739-f926-4dc3-8321-eb1c3ed5c05c.png">
> 
> 没有挂吧~，本来就是拿到数字才知道要下载几个分卷的包的 @mnnna

是我没开代理，开了就好了

**Comment by tzw-my** [comment]
@padparadsayc @mnnna 所以测试的问题？
