### ISSUE TITLE
pkg 测试

### ISSUE THREAD

**Issue by tzw-my** [x-cmd/pkg#3]
| pkg name  |   是否完成    |
| ----- | ----- |
|bit||
|brook||
|chatgpt||
|difft||
|duf||
|ffuf||
|gitleaks||
|gitui||
|goreleaser||
|gotop||
|grex||
|helix||
|hyperfine||
|k3d||
|kind||
|kube-capacity||
|kube-linter||
|kube-score||
|kubectx||
|lazygit||
|micro||
|minikube||
|mirrord||
|pandoc||
|rclone||
|sqlean||
|termshark||
|tokei||
|trdsql||
|usql||
|ws4sqlite||
|xsv||
|zenith||

**Comment by jerry8hero** [comment]
| pkg name  |   是否完成    |备注|
| ----- | ----- | ----- |
|bit|✅|
|brook|✅|
|chatgpt|❌|需要排查是否跟 x-cmd 的 chatgpt 模块冲突|
|difft|✅|
|duf|✅|
|ffuf|✅|
|gitleaks|✅|
|gitui|✅|
|goreleaser|✅|
|gotop|✅|
|grex|✅|
|helix|✅|
|hyperfine|✅|
|k3d|✅|
|kind|✅|
|kube-capacity|✅|
|kube-linter|✅|
|kube-score|✅|
|kubectx|✅|
|lazygit|✅|
|micro|✅|
|minikube|✅|
|mirrord|✅|
|pandoc|✅|
|rclone|✅|
|sqlean|❌|解压后没有 sqlean 的文件。都是.so格式的文件|
|termshark|✅|
|tokei|✅|
|trdsql|✅|
|usql|✅|
|ws4sqlite|✅|
|xsv|✅|
|zenith|✅|

**Comment by jerry8hero** [comment]
在 git-bash 环境下使用 pandoc ，报错信息如下图所示。
![image](https://user-images.githubusercontent.com/81027382/232967164-a1a48c32-6ad6-4993-9987-602bf1e43298.png)

**Comment by tzw-my** [comment]
pandoc已 fix
