### ISSUE TITLE
7za.linux.arm64 在树莓派的 arm64 环境下无法运行的问题

### ISSUE THREAD

**Issue by padparadsayc** [x-cmd/pkg#40]
如下，第一是我本机的 debian 容器，第二是远程的树莓派的设备，osarch 均是 linux/arm64 并且二进制文件是同一个（经过 md5 验证）

![image](https://github.com/x-cmd/pkg/assets/89379653/ea79bb84-1dab-4534-81ff-cae84b767d10)

![image](https://github.com/x-cmd/pkg/assets/89379653/c5b788df-9ea9-4c3b-90fc-492a07f37f1c)

**Comment by tzw-my** [comment]
@padparadsayc 这个上次开会不是说是指令级的问题么？你有结论了吗？具体有什么差异呢？

**Comment by padparadsayc** [comment]
> @padparadsayc 这个上次开会不是说是指令级的问题么？你有结论了吗？具体有什么差异呢？

上次应该是让你这边去调研吧

**Comment by padparadsayc** [comment]
同样的情况的测试在 curl 上面是可以的

![image](https://github.com/x-cmd/pkg/assets/89379653/af61f599-e8e0-4beb-bce6-0a625bde5e0f)


![image](https://github.com/x-cmd/pkg/assets/89379653/a10a518e-9e10-4292-9210-38c06defbb43)

**Comment by tzw-my** [comment]
> > @padparadsayc 这个上次开会不是说是指令级的问题么？你有结论了吗？具体有什么差异呢？
> 
> 上次应该是让你这边去调研吧

并没有指定~
树莓派那边不是一直都是你在处理吗，树莓派相关我了解不多
应该不是编译上的问题，如果是编译上的问题。那么在docker 上面应该也无法运行
起码，我们得弄清楚docker跟树莓派的运行环境的区别在哪里。

**Comment by padparadsayc** [comment]
> 并没有指定~ 树莓派那边不是一直都是你在处理吗，树莓派相关我了解不多 应该不是编译上的问题，如果是编译上的问题。那么在docker 上面应该也无法运行 起码，我们得弄清楚docker跟树莓派的运行环境的区别在哪里。

我觉得是编译方面的问题

**Comment by padparadsayc** [comment]
或者你能提供一份 7za 的编译的方案，然后我去树莓派上编译一次看看 @tzw-my

**Comment by tzw-my** [comment]
> 或者你能提供一份 7za 的编译的方案，然后我去树莓派上编译一次看看 @tzw-my

........你非要这么讲，那么gun gcc 跟 musl gcc 不能互相运行也是编译的问题了。
重点是这两个环境的区别在哪里呀，这样子就算成功了有啥用呢？

**Comment by tzw-my** [comment]
算了，我后面看吧
