### ISSUE TITLE
BUG: 生成 version.tt.json 错误

### ISSUE THREAD

**Issue by padparadsayc** [x-cmd/pkg#45]
1. 其实在 version.tt.json 的生成过程中，有不少生成出来的  json 其实都是错误的，我以 python 为例子
2. 而且为了生成这个 json 写了。八十多行的 version.sh ，明显是有问题的（难以维护）

![image](https://github.com/x-cmd/pkg/assets/89379653/429fd37f-13bd-427a-aaa7-82b7403b74d6)
![image](https://github.com/x-cmd/pkg/assets/89379653/453ad1a1-d794-42c1-9fc7-fedaea00acd7)

**Comment by padparadsayc** [comment]
而且上面这个 awk 函数因为写的太复杂了，用了一下 nawk 这边没法使用的特性，以至于拿不到 sha256

**Comment by mnnna** [comment]
![image](https://github.com/x-cmd/pkg/assets/100188748/c4f8d4af-a783-48eb-b33a-17cd9f71af38)
错误的原因是后面有些版本号不是按顺序的； 打包为什么也需要支持nawk
